version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: apps/crawler/Dockerfile
    container_name: spacecrawler-scheduler
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Supabase configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      # Optional: Override schedules for testing
      - CRAWLER_SCHEDULE_OVERRIDE=${CRAWLER_SCHEDULE_OVERRIDE:-false}
    volumes:
      - ./logs:/app/logs
    networks:
      - spacecrawler-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Development database (optional - remove if using cloud Supabase)
  postgres:
    image: postgres:15-alpine
    container_name: spacecrawler-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=spacecrawler
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spacecrawler-network
    profiles:
      - dev

  # Development web app
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: spacecrawler-web
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    networks:
      - spacecrawler-network
    profiles:
      - dev

  # Development admin app
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: spacecrawler-admin
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "3001:3001"
    networks:
      - spacecrawler-network
    profiles:
      - dev

networks:
  spacecrawler-network:
    driver: bridge

volumes:
  postgres-data: